# Generated by Django 3.2.5 on 2022-10-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogs',
            name='earned_credit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlogs',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
