# Generated by Django 3.2.5 on 2022-10-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221021_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogs',
            name='earned_credit',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=8, null=True),
        ),
    ]
